c19/gift/urls.py
from django.urls import path
from django.contrib.auth.decorators import login_required
from django.views.generic import RedirectView
from django.urls import reverse_lazy

from .views import GiftListView, ActivityListView, GiftDetailView, GiftSelectView, GiftChangeMindView, \
                    AddCommentView, EditCommentView, DeleteCommentView

app_name = 'gift'
urlpatterns = [
    path('', RedirectView.as_view(url=reverse_lazy('gift:home'))),
    path('gift-list/', login_required(GiftListView.as_view()), name="home"),
    path('activities/', login_required(ActivityListView.as_view()), name="activity_index"),
    path('<int:gift_number>/detail/', login_required(GiftDetailView.as_view()), name="gift_detail"),
    path('<int:gift_number>/select/', login_required(GiftSelectView.as_view()), name="select"),
    path('<int:gift_number>/change_mind/', login_required(GiftChangeMindView.as_view()), name="change_mind"),
    path('<int:gift_number>/comment/', login_required(AddCommentView.as_view()), name="add_comment"),
    path('<int:gift_number>/edit_comment/<int:comment_id>/',
         login_required(EditCommentView.as_view()), name="edit_comment"),
    path('<int:gift_number>/delete_comment/<int:comment_id>/',
         login_required(DeleteCommentView.as_view()), name="delete_comment"),
]

c19/recipes/urls.py
from django.urls import path
from django.views.generic.base import RedirectView
from django.contrib.auth.decorators import login_required
from django.urls import reverse_lazy

from .views import ScoreboardView, QuizPageView, QuizResultsView, RecipeView, next_quiz_results, previous_quiz_results

app_name = 'recipes'

urlpatterns = [
    path('', RedirectView.as_view(url=reverse_lazy('recipes:scoreboard'))),
    path('scoreboard/', login_required(ScoreboardView.as_view()), name='scoreboard'),
    path('quiz/<int:quiz_number>/', login_required(QuizPageView.as_view()), name='quiz_page'),
    path('results/<int:quiz_number>/', login_required(QuizResultsView.as_view()), name='quiz_results'),
    path('view/<int:recipe_id>/', login_required(RecipeView.as_view()), name='recipe_view'),
    path('next/<int:quiz_number>/', login_required(next_quiz_results), name='next_results'),
    path('previous/<int:quiz_number>/', login_required(previous_quiz_results), name='previous_results')
]

c19/recipes/models.py
from django.db import models
from django.conf import settings

import os


class QuizPage(models.Model):
    quiz_number = models.SmallIntegerField(unique=True)
    title = models.CharField(max_length=40)

    def __str__(self):
        return 'Quiz Page ' + str(self.quiz_number) + ': ' + self.title

    def is_next_quiz(self):
        if self.quiz_number < len(QuizPage.objects.all()):
            return True
        else:
            return False

        class Meta:
            ordering = ['quiz_number']


class Recipe(models.Model):
    name = models.CharField(max_length=40, unique=True)
    ingredients = models.TextField()
    quiz_page = models.ForeignKey(QuizPage, on_delete=models.CASCADE)
    recipe_image_filename = models.CharField(max_length=60, default="", blank=True)

    def __str__(self):
        return 'Recipe for ' + self.name

    def get_recipe_image_filename(self):
        return os.path.join('recipes', 'images', 'recipe_images', self.recipe_image_filename)

    class Meta:
        ordering = ['pk']


class Response(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    recipe = models.ForeignKey(Recipe, on_delete=models.CASCADE)
    guess = models.CharField(max_length=40)
    correct = models.BooleanField()

    def __str__(self):
        return self.user.username + "'s guess on " + str(self.recipe)

    def quiz_number(self):
        return self.recipe.quiz_page.page_number

c19/recipes/views.py
from django.shortcuts import render, redirect
from django.views.generic import View
from django.db.models import F
from django.contrib.auth.models import User
from django.contrib.auth import PermissionDenied

from .models import QuizPage, Recipe, Response

from user.models import get_adjusted_name

from operator import itemgetter

import utilities


class ScoreboardView(View):
    template_name = 'recipes/scoreboard.html'

    def get(self, request):
        stats, next_quiz, pages_done = self.get_stats(request.user)
        context = {'memory':utilities.get_random_memory(), 'stats':stats, 'next_quiz':next_quiz,
                   'pages_done': pages_done}
        return render(request, self.template_name, context)

    def get_stats(self, current_user):
        users = User.objects.all()
        temp = []
        for user in users:
            user_responses = Response.objects.filter(user=user)
            attempted_recipes = len(user_responses)
            if user == current_user:            # get information about the current user
                current_user_quizzes = 0
                next_quiz = None
                if attempted_recipes > 0:       # if they've done anything find out how many quiz pages they've done
                    for quiz in QuizPage.objects.all():
                        if len(user_responses.filter(recipe__quiz_page=quiz)) != 0:
                            current_user_quizzes += 1
                if len(QuizPage.objects.all()) > current_user_quizzes:      # if there are more quiz pages for them
                    next_quiz = current_user_quizzes + 1                    #    point to the next quiz page
            correct = len(user_responses.filter(correct=True))
            if attempted_recipes != 0:
                percent = '{:.1%}'.format(correct/attempted_recipes)
            else:
                percent = '0.0%'
            name = get_adjusted_name(user)
            if attempted_recipes > 0:
                temp.append({'attempted_recipes':attempted_recipes, 'correct':correct, 'percent':percent, 'name':name})
        temp_sorted = sorted(temp, key = itemgetter('attempted_recipes', 'correct'), reverse=True)
        stats = []
        attempt_group = -1
        total = len(Recipe.objects.all())
        for stat in temp_sorted:
            if stat['attempted_recipes'] == attempt_group:
                stats.append(dict(type='stat', value=stat))
            else:
                attempt_group = stat['attempted_recipes']
                stats.append(dict(type='heading', value='Completing ' + str(attempt_group) + '/' + str(total)))
                stats.append(dict(type='stat', value=stat))
        return stats, next_quiz, current_user_quizzes


class QuizPageView(View):
    template_name = 'recipes/quiz_page.html'

    def get(self, request, quiz_number):
        quiz = QuizPage.objects.get(quiz_number=quiz_number)
        recipes = Recipe.objects.filter(quiz_page=quiz)
        recipe_names = []
        for recipe in recipes:
            recipe_names.append(recipe.name)
        recipe_names.sort()
        context = {'memory':utilities.get_random_memory(), 'quiz':quiz, 'recipes':recipes, 'recipe_names': recipe_names}
        return render(request, self.template_name, context)

    def post(self, request, quiz_number):
        quiz = QuizPage.objects.get(quiz_number=quiz_number)
        recipes = Recipe.objects.filter(quiz_page=quiz)
        guesses = {}
        recipe_names = []
        for recipe in recipes:
            guesses[recipe.name] = request.POST[recipe.name]
            recipe_names.append(recipe.name)
        recipe_names.sort()
        if "" in guesses.values():
            context = {'memory': utilities.get_random_memory(), 'quiz': quiz, 'recipes': recipes, 'guesses': guesses,
                       'recipe_names': recipe_names, 'error': 'You must guess a recipe for each set of ingredients.'}
            return render(request, self.template_name, context)

        for recipe in recipes:
            response = Response(user=request.user, recipe=recipe, guess=request.POST[recipe.name])
            if recipe.name == request.POST[recipe.name]:
                response.correct = True
            else:
                response.correct = False
            response.save()
        return redirect('recipes:quiz_results', quiz_number=quiz_number)


def next_quiz_results(request, quiz_number):
    user_responses = Response.objects.filter(user=request.user)
    if len(user_responses.filter(recipe__quiz_page__quiz_number=quiz_number+1)) == 0:
        return redirect('recipes:scoreboard')
    else:
        return redirect('recipes:quiz_results', quiz_number+1)

def previous_quiz_results(request, quiz_number):
    if quiz_number == 1:
        return redirect('recipes:scoreboard')
    else:
        return redirect('recipes:quiz_results', quiz_number-1)


class QuizResultsView(View):
    template_name = 'recipes/quiz_results.html'

    def get(self, request, quiz_number):
        quiz = QuizPage.objects.get(quiz_number=quiz_number)
        results = []
        correct = 0
        for response in Response.objects.filter(user=request.user, recipe__quiz_page=quiz):
            results.append((response.recipe, response.guess))
            if response.recipe.name == response.guess:
                correct += 1
        context = {'memory':utilities.get_random_memory(), 'quiz': quiz, 'results': results, 'correct': correct}
        return render(request, self.template_name, context)


class RecipeView(View):
    template_name = 'recipes/recipe_view.html'

    def get(self, request, recipe_id):
        recipe = Recipe.objects.get(id=recipe_id)
        quiz = recipe.quiz_page
        context = {'memory': utilities.get_random_memory(), 'recipe': recipe, 'quiz_number': quiz.quiz_number}
        return render(request, self.template_name, context)

c19/recipes/templates/recipes/quiz_page.html
{% extends parent_template|default:"base.html" %}
{% load static %}
{% load recipes_extras %}

{% block content %}
    <div class="card col-md-10 mx-md-auto mb-3 px-0 border-success">
        <h2 class="card-header bg-success text-white">Recipe Quiz {{ quiz.quiz_number }}: {{ quiz.title }}</h2>
        <div class="info-box m-3 h5 text-success">
            <p class="card-title">
                Here are the recipes to match to each of the following sets of ingredients:
            </p>
            {% for name in recipe_names %}
                <p class="card-title text-center">
                    {{ name }}
                </p>
            {% endfor %}
            <p class="card-title">
                In the selection boxes below, select which or these recipes you think goes with each set of ingredients.
            </p>
        </div>
        <hr>
        <div class="card-body">
            <form action="{% url 'recipes:quiz_page' quiz.quiz_number %}" method="post">
                {% csrf_token %}
                {% if error %}
                    <div class="text-danger">
                        <p><strong>{{ error }}</strong></p>
                    </div>
                {% endif %}
                {% for recipe in recipes %}
                    <div class="row justify-content-center">
                        <div class="col preserve-whitespace
                            card-text text-center text-success">{{ recipe.ingredients }}</div>
                        <select class="col form-control form-control-lg text-success" name="{{ recipe.name }}">
                            <optgroup class="recipe-option">
                                <option></option>
                                {% for name in recipe_names %}
                                    {% if guesses %}
                                        {% if guesses|recipe_name:recipe == name %}
                                            <option class="text-success" value="{{ name }}" selected>{{ name }}</option>
                                        {% else %}
                                            <option class="text-success" value="{{ name }}">{{ name }}</option>
                                        {% endif %}
                                    {% else %}
                                        <option class="text-success" value="{{ name }}">{{ name }}</option>
                                    {% endif %}
                                {% endfor %}
                            </optgroup>
                        </select>
                    </div>
                    <hr>
                {% endfor %}
                <div class="row justify-content-center">
                    <input class="btn btn-outline-success btn-lg mt-3" type="submit" value="Submit"/>
                </div>
            </form>
        </div>
    </div>
{% endblock %}

c19/recipes/templates/recipes/quiz_results.html
{% extends parent_template|default:"base.html" %}
{% load static %}

{% block content %}
    <div class="card col-md-10 mx-md-auto mb-3 px-0 border-success">
        <h2 class="card-header bg-success text-white">Results for Recipe Quiz {{ quiz.quiz_number }}: {{ quiz.title }}</h2>
        <div class="info-box m-3 h5 text-success">
            <p class="card-title">
                You got {{ correct }} right out of {{ results|length }} on Recipe Quiz {{ quiz.quiz_number }}.
                Here is the breakdown:
            </p>
        </div>
        <hr>
        <div class="card-body">
            {% for recipe, guess in results %}
                <div class="row card-text text-success justify-content-center">
                    <div class="col-0 col-lg-3 preserve-whitespace
                    text-center text-left-lg mb-3 mb-lg-0">{{ recipe.ingredients }}</div>
                    <div class="col-0 col-lg-6">
                        <div class="row justify-content-center">
                            You guessed: {{ guess }}
                        </div>
                        <div class="row justify-content-center">
                            for {{ recipe.name }}
                        </div>
                        <div class="row justify-content-center">
                            {% if recipe.name == guess %}
                                You are Right!
                            {% else %}
                                Sorry, you guessed wrong.
                            {% endif %}
                        </div>
                    </div>
                    <div class="col-0 col-lg-3 text-center mt-3 mt-lg-0">
                        <a class="btn btn-outline-success btn-lg" href="{% url 'recipes:recipe_view' recipe.id %}">
                            Original Recipe
                        </a>
                    </div>
                </div>
                <hr>
            {% endfor %}
            <div class="row justify-content-between">
                {% if quiz.quiz_number != 1 %}
                    <a class="btn btn-outline-success btn-lg text-center"
                       href="{% url 'recipes:previous_results' quiz.quiz_number %}">
                        Previous
                    </a>
                {% else %}
                    <div> </div>
                {% endif %}
                <a class="btn btn-outline-success btn-lg text-center" href="{% url 'recipes:scoreboard' %}">
                    Scoreboard
                </a>
                {% if quiz.is_next_quiz %}
                    <a class="btn btn-outline-success btn-lg text-center"
                       href="{% url 'recipes:next_results' quiz.quiz_number %}">
                        Next
                    </a>
                {% else %}
                    <div> </div>
                {% endif %}
            </div>
        </div>
    </div>
{% endblock %}

c19/recipes/templates/recipes/recipe_view.html
{% extends parent_template|default:"base.html" %}
{% load static %}

{% block content %}
    <div class="card col-md-10 mx-md-auto mb-3 px-0 border-success">
        <h2 class="card-header bg-success text-white">{{ recipe }}</h2>
        <div class="card-body">
            <img class="card-img-top" src="{% static recipe.get_recipe_image_filename %}">
        </div>
        <div class="row justify-content-center mb-3">
            <a class="btn btn-outline-success btn-lg" href="{% url 'recipes:quiz_results' quiz_number %}">
                Return
            </a>
        </div>
    </div>
{% endblock %}

c19/recipes/templates/recipes/scoreboard.html
{% extends parent_template|default:"base.html" %}
{% load static %}

{% block content %}
    <div class="card col-md-10 mx-md-auto mb-3 px-0 border-success">
        <h2 class="card-header bg-success text-white">Recipe Game</h2>
        <div class="info-box m-3 h5 text-success">
            <p class="card-title">
                Each quiz will consist of an alphabetized set of ingredient lists from a number of different recipes.
                Your job is to select the correct recipe for each ingredient list. Watch out though, I leave certain
                ingredients off the list if their presence would be a dead giveaway. For instance, a recipe for
                something called "Strawberry Flambeau," will not have "Strawberries" listed in its ingredient list since
                that would make the correct choice a little obvious.
            </p>
            <p class="card-title">
                Click on the "Take Quiz" button if it appears below or the "See My Results" button if you have already
                taken at least one quiz.
            </p>
        </div>
        <hr>
        <div class="col-md-10 mx-md-auto">
            <div class="row justify-content-center">
                <h2 class="mx-auto text-success">Player Rankings</h2>
            </div>
            {% if stats %}
                {% for stat in stats %}
                    {% if stat.type == "heading" %}
                        <hr>
                        <div class="row justify-content-center">
                            <h3 class="text-success">{{ stat.value }}</h3>
                        </div>
                    {% else %}
                        <div class="row justify-content-center">
                            <h4 class="text-success">{{ stat.value.name }}:  {{ stat.value.percent }}</h4>
                        </div>
                    {% endif %}
                {% endfor %}
            {% else %}
                <p class="text-success">No rankings yet available.</p>
            {% endif %}
            </div>
            <hr>
            <div class="col-md-10 mx-md-auto">
                <div class="row justify-content-around mb-3">
                {% if next_quiz %}
                    <a class="btn btn-outline-success text-center"
                       href="{% url 'recipes:quiz_page' next_quiz %}">Take Quiz</a>
                {% endif %}
                {% if pages_done > 0 %}
                    <a class="btn btn-outline-success text-center"
                       href="{% url 'recipes:quiz_results' 1 %}">See My Results</a>
                {% endif %}
                </div>
            </div>
        </div>
    </div>
{% endblock %}