c19/gift/urls.py
from django.urls import path
from django.contrib.auth.decorators import login_required
from django.views.generic import RedirectView
from django.urls import reverse_lazy

from .views import GiftListView, ActivityListView, GiftDetailView, GiftSelectView, GiftChangeMindView, \
                    AddCommentView, EditCommentView, DeleteCommentView

app_name = 'gift'
urlpatterns = [
    path('', RedirectView.as_view(url=reverse_lazy('gift:home'))),
    path('gift-list/', login_required(GiftListView.as_view()), name="home"),
    path('activities/', login_required(ActivityListView.as_view()), name="activity_index"),
    path('<int:gift_number>/detail/', login_required(GiftDetailView.as_view()), name="gift_detail"),
    path('<int:gift_number>/select/', login_required(GiftSelectView.as_view()), name="select"),
    path('<int:gift_number>/change_mind/', login_required(GiftChangeMindView.as_view()), name="change_mind"),
    path('<int:gift_number>/comment/', login_required(AddCommentView.as_view()), name="add_comment"),
    path('<int:gift_number>/edit_comment/<int:comment_id>/',
         login_required(EditCommentView.as_view()), name="edit_comment"),
    path('<int:gift_number>/delete_comment/<int:comment_id>/',
         login_required(DeleteCommentView.as_view()), name="delete_comment"),
]

c19/trivia/urls.py
from django.urls import path
from django.views.generic.base import RedirectView
from django.contrib.auth.decorators import login_required
from django.urls import reverse_lazy

from .views import (ScoreboardView, NextQuestionView, DisplayQuestionView, DisplayResultView,
                    previous_question_view, next_question_view, save_trivia_view)

app_name = 'trivia'

urlpatterns = [
    path('', RedirectView.as_view(url=reverse_lazy('trivia:scoreboard'))),
    path('scoreboard/', login_required(ScoreboardView.as_view()), name='scoreboard'),
    path('question/', login_required(NextQuestionView.as_view()), name='next_question'),
    path('question/<int:question_number>/', login_required(DisplayQuestionView.as_view()), name='display_question'),
    path('result/<int:question_number>/<int:choice_id>/', login_required(DisplayResultView.as_view()), name='result'),
    path('previous/<int:question_number>/', login_required(previous_question_view), name='previous'),
    path('next/<int:question_number>/', login_required(next_question_view), name='next'),
    path('save/', login_required(save_trivia_view), name='save_files')
]

c19/trivia/models.py
from django.db import models
from django.conf import settings

from user.models import get_adjusted_name


class TriviaQuestion(models.Model):
    number = models.IntegerField(unique=True)
    text = models.CharField(max_length=255)
    publish = models.BooleanField(default=False)
    attempted_count = models.IntegerField(default=0)
    correct_count = models.IntegerField(default=0)
    explanation = models.CharField(max_length=255, default="", blank=True)
    link = models.URLField(default="", blank=True)

    def __str__(self):
        return self.text

    class Meta:
        ordering = ['number']


class TriviaChoice(models.Model):
    question = models.ForeignKey(TriviaQuestion, on_delete=models.CASCADE)
    choice_text = models.CharField(max_length=255)
    correct = models.BooleanField(default=False)

    def __str__(self):
        return self.choice_text


    class Meta:
        ordering = ['pk']


class TriviaResponse(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    question = models.ForeignKey(TriviaQuestion, on_delete=models.CASCADE)
    response = models.ForeignKey(TriviaChoice, on_delete=models.CASCADE)
    correct = models.BooleanField(default=False)

    def __str__(self):
        text = get_adjusted_name(self.user) + ' responded ' + \
               str(self.response) + ' to question ' + str(self.question.number)
        return text


    class Meta:
        ordering = ['question']


class TriviaConversation(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    entry = models.CharField(max_length = 300)

    def __str__(self):
        return get_adjusted_name(self.user) + ': ' + self.entry

c19/trivia/views.py
from django.shortcuts import render, redirect
from django.views.generic import View
from django.contrib.auth.models import User
from django.urls import reverse

from .models import TriviaQuestion, TriviaChoice, TriviaResponse
from user.models import get_adjusted_name

from operator import itemgetter

import utilities

def get_next_question(user):
    next_question = len(TriviaResponse.objects.filter(user=user)) + 1
    return next_question

class ScoreboardView(View):
    template_name = 'trivia/scoreboard.html'

    def get(self, request):
        stats, current_user_attempts = self.get_stats(request.user)
        context = {'memory':utilities.get_random_memory(), 'stats':stats, 'user_attempts':current_user_attempts}
        return render(request, self.template_name, context)

    def get_stats(self, current_user):
        users = User.objects.all()
        temp = []
        for user in users:
            user_responses = TriviaResponse.objects.filter(user=user)
            attempted_questions = len(user_responses)
            if user == current_user:
                current_user_attempts = attempted_questions
            correct = len(user_responses.filter(correct=True))
            if attempted_questions != 0:
                percent = '{:.1%}'.format(correct/attempted_questions)
            else:
                percent = '0.0%'
            name = get_adjusted_name(user)
            if attempted_questions > 0:
                temp.append( {'attempted_questions':attempted_questions, 'correct':correct, 'percent':percent, 'name':name} )
        temp_sorted = sorted(temp, key = itemgetter('attempted_questions', 'correct'), reverse=True)
        stats = []
        attempt_group = -1
        total = len(TriviaQuestion.objects.all())
        for stat in temp_sorted:
            if stat['attempted_questions'] == attempt_group:
                stats.append(dict(type='stat', value=stat))
            else:
                attempt_group = stat['attempted_questions']
                stats.append(dict(type='heading', value='Completing ' + str(attempt_group) + '/' + str(total)))
                stats.append(dict(type='stat', value=stat))
        return stats, current_user_attempts


class NextQuestionView(View):

    def get(self, request):
        return redirect('trivia:display_question', get_next_question(request.user))


class DisplayQuestionView(View):
    template_name = 'trivia/trivia_question.html'

    def get(self, request, question_number):
        try:                                                                # prevents going beyond end of questions
            question = TriviaQuestion.objects.get(number=question_number)
        except:
            question_number = get_next_question(request.user)
            return redirect('trivia:display_question', question_number=question_number) # goes to user's next question
        else:
            if int(question_number) > get_next_question(request.user):      # prevents going beyond user's next question
                question_number = get_next_question(request.user)
                return redirect('trivia:display_question', question_number=question_number)
            if int(question_number) < get_next_question(request.user):      # prevents answering a question twice
                response = TriviaResponse.objects.get(user=request.user, question=question).response
                return redirect('trivia:result', question_number=question.number, choice_id=response.id)
            choices = question.triviachoice_set.all()
            context = {'memory':utilities.get_random_memory(), 'question':question, 'choices':choices}
            return render(request, self.template_name, context)

    def post(self, request, question_number):
        question = TriviaQuestion.objects.get(number=question_number)
        choices = question.triviachoice_set.all()
        if int(question_number) < get_next_question(request.user):
            user_response = TriviaResponse.objects.get(user=request.user, question=question)
            choice = user_response.response
            return redirect('trivia:result', question_number=question_number, choice_id=choice.id)
        try:
            choice_id = request.POST['choice']
        except KeyError:
            context = {'question': question, 'choices': choices, 'display_memory': utilities.get_random_memory(),
                       'error_message': 'You must choose one of the responses below.'}
            return render(request, self.template_name, context)
        else:
            choice = choices.get(id=choice_id)
            user_response = TriviaResponse(user=request.user, question=question, response=choice)
            user_response.correct = choice.correct
            user_response.save()
            question.attempted_count += 1
            if choice.correct:
                question.correct_count += 1
            question.save()
        return redirect('trivia:result', question_number=question_number, choice_id = choice.id)


class DisplayResultView(View):
    template_name = 'trivia/trivia_result.html'

    def get(self, request, question_number, choice_id):
        if int(question_number) >= get_next_question(request.user):  # prevents going beyond user's next question
            question_number = get_next_question(request.user)
            return redirect('trivia:display_question', question_number=question_number)
        question = TriviaQuestion.objects.get(number=question_number)
        user_choice = TriviaChoice.objects.get(id=choice_id)
        choices = question.triviachoice_set.all()
        correct_choice = question.triviachoice_set.get(correct=True)
        context = {'memory': utilities.get_random_memory(), 'question': question, 'choices': choices,
                   'user_choice': user_choice, 'correct_choice': correct_choice}
        return render(request, self.template_name, context)

def previous_question_view(request, question_number):
    previous = question_number - 1
    if previous < 1:
        previous = len(TriviaQuestion.objects.all())
    return redirect('trivia:display_question', previous)

def next_question_view(request, question_number):
    next = question_number + 1
    if next > len(TriviaQuestion.objects.all()):
        next = 1
    return redirect('trivia:display_question', next)

def save_trivia_view(request):
    questions = TriviaQuestion.objects.all()
    question_list = []
    answer_list = []
    question_number = 1
    for question in questions:
        question_list.append(str(question_number) + '. ' + str(question) + '\n')
        answer_list.append(str(question_number) + '. ' + str(question) + '\n')
        question_number += 1
        choices = question.triviachoice_set.all()
        choice_label = 'A'
        for choice in choices:
            question_list.append('\t' + choice_label + ') ' + str(choice) + '\n')
            if choice.correct:
                answer_list.append('\t' + choice_label + ') ' + str(choice).upper() + ' <--correct\n')
            else:
                answer_list.append('\t' + choice_label + ') ' + str(choice) + '\n')
            choice_label = chr(ord(choice_label) + 1)
        question_list.append('\n')
        if question.explanation:
            answer_list.append('Explanation: ' + str(question.explanation) + '\n')
        if question.link:
            answer_list.append('See: ' + str(question.link) + '\n')
        answer_list.append('\n')
    question_file = open('Christmas_Trivia_Questions.txt', 'w')
    question_file.writelines(question_list)
    question_file.close()
    answer_file = open('Christmas_Trivia_Answers.txt', 'w')
    answer_file.writelines(answer_list)
    answer_file.close()
    return redirect('trivia:scoreboard')

c19/trivia/templates/trivia/scoreboard.html
{% extends parent_template|default:"base.html" %}
{% load static %}

{% block content %}
    <div class="card col-md-10 mx-md-auto mb-3 px-0 border-success">
        <h2 class="card-header bg-success text-white">Christmas Trivia Game</h2>
        <div class="info-box m-3 h5">
            <p class="card-title">Here are the rules:</p>
            <ol>
                <li>Questions must be answered in order.</li>
                <li>Questions may only be answered once. You may see your previous answers, but you may not change
                them.</li>
                <li>Players must answer questions from their own knowledge without getting information from electronic
                devices, books, or elsewhere.</li>
                <li>The website will enforce rules 1 and 2. You are on the honor system for rule 3.</li>
            </ol>
        </div>
        <hr>
        <div class="col-md-10 mx-md-auto">
            <div class="row justify-content-center">
                <h2 class="mx-auto text-success">Player Rankings</h2>
            </div>
            {% if stats %}
                {% for stat in stats %}
                    {% if stat.type == "heading" %}
                        <hr>
                        <div class="row justify-content-center">
                            <h3 class="text-success">{{ stat.value }}</h3>
                        </div>
                    {% else %}
                        <div class="row justify-content-center">
                            <h4 class="text-success">{{ stat.value.name }}:  {{ stat.value.percent }}</h4>
                        </div>
                    {% endif %}
                {% endfor %}
            {% else %}
                <p class="text-success">No rankings yet available.</p>
            {% endif %}
        </div>
        <hr>
        <div class="col-md-10 mx-md-auto">
            <div class="row justify-content-center mb-3">
                {% if user_attempts == 0 %}
                    <a class="btn btn-outline-success text-center"
                       href="{% url 'trivia:next_question' %}">First Question
                    </a>
                {% else %}
                    <a class="btn btn-outline-success mx-auto text-center"
                       href="{% url 'trivia:next_question' %}">Next Question
                    </a>
                {% endif %}
            </div>
        </div>
        {% if user.is_superuser %}
            <div class="col-md-10 mx-md-auto">
                <div class="row justify-content-center mb-3">
                    <a class="btn btn-outline-success text-center"
                       href="{% url 'trivia:save_files' %}">Save Question and Answer Files
                    </a>
                </div>
            </div>
        {% endif %}
    </div>
{% endblock %}

c19/trivia/templates/trivia/trivia_question.html
{% extends parent_template|default:"base.html" %}
{% load static %}

{% block content %}
    <div class="row">
        <div class="card col-md-10 mx-md-auto px-0 border-success">
            <h2 class="card-header bg-success text-white">Trivia Question: {{ question.number }}</h2>
            <div class="card-body">
                <form action="{% url 'trivia:display_question' question.number %}" method="post">
                    {% csrf_token %}
                    <h3 class="card-title text-success">{{ question }}</h3>
                    {% if error_message %}
                        <div class="text-danger">
                            <p><strong>{{ error_message }}</strong></p>
                        </div>
                    {% endif %}
                    {% for choice in choices %}
                        <div class="form-check">
                            <label class="form-check-label text-success mb-3 ml-sm-3 ml-md-5">
                                <input class="form-check-input" type="radio" name="choice" value={{ choice.id }}>
                                {{ choice }}
                            </label>
                        </div>
                    {% endfor %}
                    <div class="row justify-content-center">
                        <input class="btn btn-outline-success btn-lg mt-3" type="submit" value="Submit" name="trivia_submit"/>
                    </div>
                </form>
            </div>
        </div>
    </div>
{% endblock %}

c19/trivia/templates/trivia/trivia_result.html
{% extends parent_template|default:"base.html" %}
{% load static %}

{% block content %}
    <div class="card col-md-10 mx-md-auto px-0 border-success">
        <h2 class="card-header bg-success text-white">Your Results on Trivia Question: {{ question.number }}</h2>
        <div class="card-body">
            <h4 class="card-title text-success">{{ question }}</h4>
            <ul class="list-group card-text">
                {% for choice in choices %}
                    {% if choice == user_choice %}
                        {% if choice == correct_choice %}
                            <li class="list-group-item bg-success text-white">
                                {{ choice }} <-- Your Response
                            </li>
                        {% else %}
                            <li class="list-group-item text-danger">
                                {{ choice }} <-- Your Response
                            </li>
                        {% endif %}
                    {% else %}
                        {% if choice == correct_choice %}
                            <li class="list-group-item bg-success text-white">
                                {{ choice }}
                            </li>
                        {% else %}
                            <li class="list-group-item text-success">
                                {{ choice }}
                            </li>
                        {% endif %}
                    {% endif %}
                {% endfor %}
            </ul>
            {% if user_choice == correct_choice %}
                <h5 class="card-text text-success mt-3 mx-md-5">You got it right!</h5>
            {% else %}
                <h5 class="card-text text-success mt-3 mx-md-5">Sorry, that's not right. The correct response is: {{ correct_choice }}</h5>
            {% endif %}
            {% if question.explanation %}
                <div class="card-text text-blue mt-3 mx-md-5">
                    <h5>Explanation: </h5>
                    {{ question.explanation }}
                </div>
            {% endif %}
            {% if question.link %}
                <div class="card-text mx-md-5">
                    <a href="{{ question.link }}">Click or tap here for more information.</a>
                </div>
            {% endif %}
            <hr>
            <div class="row justify-content-between">
                <a class="btn btn-outline-success btn-lg col-1 col-md-3" href="{% url 'trivia:previous' question.number %}">
                    <span class="d-md-none"><i class="fas fa-angle-left"></i></span>
                    <span class="d-none d-md-inline">Previous</span>
                </a>
                <a class="btn btn-outline-success btn-lg col-6 col-md-3" href="{% url 'trivia:scoreboard' %}">
                    Scoreboard
                </a>
                <a class="btn btn-outline-success btn-lg col-1 col-md-3" href="{% url 'trivia:next' question.number %}">
                    <span class="d-md-none"><i class="fas fa-angle-right"></i></span>
                    <span class="d-none d-md-inline">Next</span>
                </a>
            </div>
        </div>
    </div>
{% endblock %}