c19/gift/urls.py
from django.urls import path
from django.contrib.auth.decorators import login_required
from django.views.generic import RedirectView
from django.urls import reverse_lazy

from .views import GiftListView, ActivityListView, GiftDetailView, GiftSelectView, GiftChangeMindView, \
                    AddCommentView, EditCommentView, DeleteCommentView

app_name = 'gift'
urlpatterns = [
    path('', RedirectView.as_view(url=reverse_lazy('gift:home'))),
    path('gift-list/', login_required(GiftListView.as_view()), name="home"),
    path('activities/', login_required(ActivityListView.as_view()), name="activity_index"),
    path('<int:gift_number>/detail/', login_required(GiftDetailView.as_view()), name="gift_detail"),
    path('<int:gift_number>/select/', login_required(GiftSelectView.as_view()), name="select"),
    path('<int:gift_number>/change_mind/', login_required(GiftChangeMindView.as_view()), name="change_mind"),
    path('<int:gift_number>/comment/', login_required(AddCommentView.as_view()), name="add_comment"),
    path('<int:gift_number>/edit_comment/<int:comment_id>/',
         login_required(EditCommentView.as_view()), name="edit_comment"),
    path('<int:gift_number>/delete_comment/<int:comment_id>/',
         login_required(DeleteCommentView.as_view()), name="delete_comment"),
]

c19/mail/urls.py
from django.urls import path
from django.contrib.auth.decorators import login_required

from .views import SendMail

app_name = 'mail'

urlpatterns = [
    path('', login_required(SendMail.as_view()), name='send-mail'),
]

c19/user/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from django.views.generic import RedirectView

app_name = 'user'
urlpatterns = [
    path('login/', auth_views.LoginView.as_view(template_name='user/login.html', redirect_authenticated_user=True),
         name='login'),
    path('logout/', auth_views.LogoutView.as_view(template_name='user/logout.html'), name='logout'),
]

c19/templates/base.html
{% load static %}

<! DOCTYPE html >

<html lang="en">

    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <meta http-equiv="X-UA-Compatible" content="ie=edge">
        <link href="https://fonts.googleapis.com/css?family=Great+Vibes|Open+Sans" rel="stylesheet">
        <link rel="shortcut icon" href="{% static 'images/favicon.ico' %}" type="image/x-icon" />
        <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.3.1/css/all.css"
              integrity="sha384-mzrmE5qonljUremFsqc01SB46JvROS7bZs3IO2EmfFsd15uHvIt+Y8vEf7N7fWAU" crossorigin="anonymous">
        <!--<link rel="stylesheet" href="{% static '/css/bootstrap.css' %}">-->
        <!--<link rel="stylesheet" type="text/css" href="{% static '/css/custom.css' %}">-->
        <link rel="stylesheet" type="text/css" href="{% static '/css/styles.css' %}">

        {% block title %}<title>Christmas 2019{% endblock %}</title>

        {% block head %}
        {% endblock %}

    </head>

    <body>

        {% include "header.html" %}

        <main>
            <div class="container">
                {% block content %}
                {% endblock %}
            </div>
        </main>

        {% include "footer.html" %}



        <script
        src="https://code.jquery.com/jquery-3.3.1.min.js"
        integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8="
        crossorigin="anonymous"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49"
            crossorigin="anonymous"></script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy"
            crossorigin="anonymous"></script>

        <script>
            // Get the current year for the copyright
            $('#year').text(new Date().getFullYear());
        </script>

        {% block body %}
        {% endblock %}

    </body>

</html>

c19/templates/footer.html
{% load static %}

{% block footer %}

    <footer>
        <p class="text-small text-center mt-3">
            Merry Christmas 2019!
        </p>
    </footer>


{% endblock %}

c19/templates/header.html
{% load static %}

{% block header %}

    <header>
        <div class="container">
            <div class="row">
                <div class="col-md-2 d-none d-md-inline">
                    <a href="{% url 'gift:home' %}" class="brand">
                        <img src="{% static 'images/ThreeOrnamentsAlpha.png' %}" class="img-fluid">
                    </a>
                </div>
                <div class="col">
                    <!-- Banner Heading -->
                    <div class="row">
                        <div class="col">
                            <a href="{% url 'gift:home' %}">
                                <h1 class="header-text d-inline">Christmas 2019</h1>
                            </a>
                        </div>
                    </div>
                    <!-- Welcome and Login/Logout Links -->
                    <div class="row align-items-top">
                        <div class="col-6">
                            {% if user.is_authenticated %}
                                <span class="h5">Welcome {{ user.first_name }}!</span>
                                <a class="link" href="{% url 'user:logout' %}">  (Logout)</a>
                            {% else %}
                                <span class="h5">Welcome!</span>
                                <a class="link" href="{% url 'user:login' %}?next={{ request.path_info }}">  (Login)</a>
                            {% endif %}
                        </div>
                        <!-- Menu Links -->
                        <div class="col">
                            <nav class="navbar navbar-light navbar-expand-lg pt-0">
                                <button class="navbar-toggler ml-auto p-0 pb-3" type="button"
                                        data-toggle="collapse" data-target="#navbarCollapse">
                                    <span class="navbar-toggler-icon pt-1" style="background:none">
                                        <i class="fas fa-bars"></i>
                                    </span>
                                </button>
                                <div class="collapse navbar-collapse" id="navbarCollapse">
                                    <div class="navbar-nav ml-auto nav-fill">
                                        {% if user.is_staff %}
                                            <a href="{% url 'mail:send-mail' %}?next={{ next_url }}"
                                               class="nav-item nav-link btn btn-outline-primary btn-lg text-right pb-3">
                                                E-mail
                                            </a>
                                        {% endif %}
                                        <a href="{% url 'gift:home' %}"
                                           class="nav-item nav-link btn btn-outline-primary btn-lg text-right pb-3">
                                            Gifts
                                        </a>
                                        <a href="{% url 'memory:memory_list' %}"
                                           class="nav-item nav-link btn btn-ouline-primary btn-lg text-right pb-3">
                                            Memories
                                        </a>
                                        <a href="{% url 'gift:activity_index' %}"
                                           class="nav-item nav-link btn btn-outline-primary btn-lg text-right pb-3">
                                            Activities
                                        </a>
                                    </div>
                                </div>
                            </nav>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </header>
    <!-- Memory Block -->
    {% if user.is_authenticated %}
        <div class="container">
            <div class="row">
                {% if memory %}
                    <div class="col memory p-3 m-3 mb-0">
                            <a class="d-md-none" data-toggle="collapse" href="#memory"><span>{{ memory.author }}...</span></a>
                            <span class="d-none d-md-inline">{{ memory.author }}</span>
                            <span class="d-md-none collapse" id="memory">{{ memory }}</span>
                            <span class="d-none d-md-inline">{{ memory }}</span>
                    </div>
                {% endif %}
            </div>
        </div>
    {% endif %}

{% endblock %}