c19/gift/urls.py
from django.urls import path
from django.contrib.auth.decorators import login_required
from django.views.generic import RedirectView
from django.urls import reverse_lazy

from .views import GiftListView, ActivityListView, GiftDetailView, GiftSelectView, GiftChangeMindView, \
                    AddCommentView, EditCommentView, DeleteCommentView

app_name = 'gift'
urlpatterns = [
    path('', RedirectView.as_view(url=reverse_lazy('gift:home'))),
    path('gift-list/', login_required(GiftListView.as_view()), name="home"),
    path('activities/', login_required(ActivityListView.as_view()), name="activity_index"),
    path('<int:gift_number>/detail/', login_required(GiftDetailView.as_view()), name="gift_detail"),
    path('<int:gift_number>/select/', login_required(GiftSelectView.as_view()), name="select"),
    path('<int:gift_number>/change_mind/', login_required(GiftChangeMindView.as_view()), name="change_mind"),
    path('<int:gift_number>/comment/', login_required(AddCommentView.as_view()), name="add_comment"),
    path('<int:gift_number>/edit_comment/<int:comment_id>/',
         login_required(EditCommentView.as_view()), name="edit_comment"),
    path('<int:gift_number>/delete_comment/<int:comment_id>/',
         login_required(DeleteCommentView.as_view()), name="delete_comment"),
]

c19/gift/models.py
from django.db import models
from django.conf import settings

from base_classes import AuthorName
from user.models import get_adjusted_name

import os


class Gift(models.Model):
    gift_number = models.SmallIntegerField()
    description = models.TextField()
    wrapped = models.BooleanField(default=True)
    selected = models.BooleanField(default=False)
    receiver = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, null=True, blank=True)

    class Meta:
        ordering = ['gift_number']

    def __str__(self):
        return 'Gift ' + str(self.gift_number)

    def get_image_filename(self):
        if self.wrapped:
            status = 'wrapped'
        else:
            status = 'unwrapped'
        return os.path.join('gift', 'images', status, str(self) + '.png')

    def get_thumbnail_filename(self):
        if self.wrapped:
            status = 'wrapped'
        else:
            status = 'unwrapped'
        return os.path.join('gift', 'images', status, 'thumbnails', str(self) + '.png')

    def get_comments(self):
        comments = Comment.objects.filter(gift=self)
        return comments

    def receiver_name(self):
        return get_adjusted_name(self.receiver)


class Comment(AuthorName):
    gift = models.ForeignKey(Gift, on_delete=models.CASCADE)
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    comment = models.TextField()

    def __str__(self):
        if len(self.comment) > 10:
            return self.comment[0:9] + '...'
        else:
            return self.comment

    def display(self):
        prefix = self.get_name(self.user) + ' says: '
        return prefix + self.comment

c19/whatsit/models.py
from django.db import models
from django.conf import settings

from user.models import get_adjusted_name

import os


class Object(models.Model):
    ONE = '1'
    TWO = '2'
    THREE = '3'
    STAGE_CHOICES = (
        (ONE, 'one'),
        (TWO, 'two'),
        (THREE, 'three')
    )
    number = models.SmallIntegerField(unique=True)
    publish = models.BooleanField(default=False)
    stage = models.CharField(max_length=1, choices=STAGE_CHOICES, default=ONE)
    correct_description = models.CharField(max_length=500)

    class Meta:
        ordering = ['number']

    def __str__(self):
        return 'Object ' + str(self.number)

    def description_count(self):
        return len(Description.objects.filter(object=self))

    def image_filename(self):
        return os.path.join('whatsit', 'images', str(self) + '.png')

    def vote_count(self):
        """
        returns the combined number of votes cast on descriptions for this object
        :return: integer
        """
        return len(Contribution.objects.filter(type=Contribution.VOTE))


class Description(models.Model):
    object = models.ForeignKey(Object, on_delete=models.CASCADE)
    author = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    description = models.CharField(max_length=500)
    votes = models.SmallIntegerField(default=0)

    def __str__(self):
        return self.author.username + "'s description of Object " + str(self.object.number)


class Contribution(models.Model):
    DESCRIPTION = 'DE'
    VOTE = 'VO'
    TYPE_CHOICES = (
        (DESCRIPTION, 'Description'),
        (VOTE, 'Vote')
    )
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    object = models.ForeignKey(Object, on_delete=models.CASCADE)
    type = models.CharField(max_length=2, choices=TYPE_CHOICES)

    def __str__(self):
        return self.user.username + "'s " + self.get_type_display() + " for " + str(self.object)

c19/gift/views.py
from django.shortcuts import render, redirect
from django.urls import reverse
from django.views import View
from django.contrib.auth import PermissionDenied
from django.utils.http import is_safe_url

from .models import Gift, Comment

import utilities

class GiftListView(View):
    template = 'gift/gift_list.html'

    def get(self, request):
        gifts = Gift.objects.all()
        context = {'gifts': gifts, 'user_has_gift': utilities.user_has_gift(request.user),
                   'memory': utilities.get_random_memory()}
        return render(request, self.template, context)


class ActivityListView(View):
    template = 'gift/activity_list.html'

    def get(self, request):
        context = {'memory': utilities.get_random_memory()}
        return render(request, self.template, context)



class GiftDetailView(View):
    template = 'gift/gift_detail.html'

    def get(self, request, gift_number):
        try:
            gift = Gift.objects.get(gift_number=gift_number)
        except:
            return redirect('gift:home')
        comments = gift.comment_set.all()
        next_url = request.path
        context = {'gift': gift, 'comments':comments, 'user_has_gift':utilities.user_has_gift(request.user),
                   'next_url':next_url, 'memory':utilities.get_random_memory()}
        return render(request, self.template, context)


class GiftSelectView(View):

    def post(self, request, gift_number):
        try:
            current_gift = Gift.objects.get(gift_number=gift_number)
        except:
            return redirect('gift:home')
        if request.POST['button'] == 'remark':
            return redirect('gift:add_comment', gift_number)
        current_gift.selected = True
        current_gift.receiver = request.user
        current_gift.save()
        return redirect(reverse('gift:home'))


class GiftChangeMindView(View):

    def post(self, request, gift_number):
        try:
            current_gift = Gift.objects.get(gift_number=gift_number)
        except:
            return redirect('gift:home')
        if request.POST['button'] == 'remark':
            return redirect('gift:add_comment', gift_number)
        current_gift = Gift.objects.get(gift_number=gift_number)
        current_gift.selected = False
        current_gift.receiver = None
        current_gift.save()
        return redirect(reverse('gift:home'))


class AddCommentView(View):
    template_name = 'gift/comment_create.html'

    def get(self, request, gift_number):
        gift = Gift.objects.get(gift_number=gift_number)
        comments = gift.comment_set.all()
        context = {'gift':gift, 'comments':comments, 'memory':utilities.get_random_memory()}
        return render(request, self.template_name, context)

    def post(self, request, gift_number):
        gift = Gift.objects.get(gift_number=gift_number)
        # Needs a check for an empty request.POST['comment_text']. Should only save comment if there is one.
        # Otherwise is should go back to the create_comment page with an error message
        # The create_comment page should also have a cancel button to escape without adding a comment.
        new_comment = Comment(gift=gift, user=request.user, comment=request.POST['comment_text'])
        new_comment.save()
        return redirect('gift:home')

class EditCommentView(View):
    template_name = 'gift/comment_edit.html'

    def get(self, request, gift_number, comment_id):
        try:
            gift = Gift.objects.get(gift_number=gift_number)
            selected_comment = Comment.objects.get(pk=comment_id)
        except:
            return redirect('gift:home')
        comments = gift.comment_set.all()
        next_url = request.GET.get('next', '')
        if next_url:
            if not is_safe_url(next_url, request.get_host()):
                next_url = ''
        if request.user == selected_comment.user:
            context = {'gift':gift, 'comments':comments, 'selected_comment':selected_comment, 'next_url':next_url,
                   'memory':utilities.get_random_memory()}
            return render(request, self.template_name, context)
        else:
            raise PermissionDenied

    def post(self, request, gift_number, comment_id):
        comment = Comment.objects.get(pk=comment_id)
        if request.user == comment.user:
            comment.comment = request.POST['comment_text']
            comment.save()
            return redirect('gift:home')
        else:
            raise PermissionDenied


class DeleteCommentView(View):
    template_name = 'gift/comment_delete.html'

    def get(self, request, gift_number, comment_id):
        try:
            gift = Gift.objects.get(gift_number=gift_number)
            comment = Comment.objects.get(pk=comment_id)
        except:
            return redirect('gift:home')
        comments = gift.comment_set.all()
        next_url = request.GET.get('next', '')
        if next_url:
            if not is_safe_url(next_url, request.get_host()):
                next_url = ''
        if request.user == comment.user:
            context = {'gift':gift, 'comments':comments, 'selected_comment':comment, 'next_url':next_url,
                       'memory':utilities.get_random_memory()}
            return render(request, self.template_name, context)

    def post(self, request, gift_number, comment_id):
        try:
            gift = Gift.objects.get(gift_number=gift_number)
            comment = Comment.objects.get(pk=comment_id)
        except:
            return redirect('gift:home')
        if request.POST['button'] != 'delete':      # user clicked the cancel button
            next_url = request.POST.get('next', '')
            if next_url:
                if is_safe_url(next_url, request.get_host()):
                    return redirect(next_url)
            return redirect('gift:edit_comment', gift.gift_number, comment_id)
        else:
            if request.user == comment.user:
                comment.delete()
                return redirect('gift:home')
            else:
                raise PermissionDenied

c19/gift/templates/gift/activity_list.html
{% extends parent_template|default:"base.html" %}
{% load static %}

{% block content %}
    <div class="card border-success col-md-10 mx-md-auto mb-3 px-0">
        <h2 class="card-header bg-success text-white">
            Choose an Activity
        </h2>
        <h4 class="card-title text-success mt-3 mb-0 px-5">
            This page launches Christmas games and activities for us to enjoy. Check back from time to time
            to see if I've added anything new.
        </h4>
        <div class=" card-body text-success pt-0">
            <hr>
            <div class="row">
                <div class="col-md-8 card-text">
                    <h5>Trivia Game</h5>
                    <p>
                        Compete with other family members for the best score in a Christmas Trivial game. You're on
                        the honor system here. No fair asking Alexa or Siri or whatever other cybernetic voices there
                        may be, and no looking things up in books or on the internet. Just trust your own mind.
                    </p>
                </div>
                <div class="col-md-4 mt-3 mt-md-0">
                    <a class="btn btn-outline-info btn-block" href="{% url 'trivia:scoreboard' %}">Play Trivia Game</a>
                </div>
            </div>
            <hr>
            <div class="row">
                <div class="col-md-8 card-text">
                    <h5>What Is It?</h5>
                    <p>
                        Ever hear of a game called "Fictionary?" This is something like it. Given a picture of a not
                        exactly everyday object, try to convince people that you know what it is. Then, seeing only the
                        descriptions, not their authors, vote for what you think is the most believable one that is not
                        your own. Finally the authors, the votes and the actual description of the object will all be
                        revealed.
                    </p>
                </div>
                <div class="col-md-4 mt-3 mt-md-0">
                    <a class="btn btn-outline-info btn-block" href="{% url 'whatsit:object_list' %}">
                        Play What Is It?
                    </a>
                </div>
            </div>
            <hr>
            <div class="row">
                <div class="col-md-8 card-text">
                    <h5>Recipe Game</h5>
                    <p>
                        Janet supplied some old recipes from Aunt Helen O'Brien that form the basis for this game. Based
                        only on the ingredients, can you guess what Aunt Helen was making? After you've made your
                        guesses you will be able to see scans of the original recipes. Perhaps you would like to try to
                        make these things yourself.
                    </p>
                </div>
                <div class="col-md-4 mt-3 mt-md-0">
                    <a class="btn btn-outline-info btn-block" href="{% url 'recipes:scoreboard' %}">
                        Play the Recipe Game
                    </a>
                </div>
            </div>
            <hr>
        </div>
    </div>
{% endblock %}

c19/gift/templates/gift/base_gift_detail.html
{% extends parent_template|default:"base.html" %}
{% load static %}

{% block content %}
    <div class="card col col-md-10 mx-auto mb-3 border-primary px-0">
        <img class="card-img-top" src="{% static gift.get_image_filename %}" alt="Image of {{ gift }}">
        <div class="card-body">
            <div class="row card-title justify-content-between">
                {% if gift.selected %}
                    <div class="h4 text-primary d-sm-inline col-sm-5">{{ gift }}</div>
                    <div class="h5 text-primary d-sm-inline col-sm-5 text-sm-right">Selected by {{ gift.receiver_name }}</div>
                {% else %}
                    <div class="h4 text-success d-sm-inline col-sm-5">{{ gift }}</div>
                    <div class="h5 text-success d-sm-inline col-sm-5 text-sm-right">Currently Unselected</div>
                {% endif %}
            </div>
            {% for comment in comments %}
                {% if comment == selected_comment %}
                    <p class="card-text comment font-weight-bold">{{ comment.display }}</p>
                {% else %}
                    <p class="card-text comment">
                        {{ comment.display }}
                        <a href="{% url 'gift:edit_comment' gift.gift_number comment.pk %}?next={{ next_url }}"> (Edit...)</a>
                    </p>
                {% endif %}
            {% endfor %}
            <div class="info-box mb-3">
                {% block gift-detail-page-specific-content %}
                {% endblock %}
            </div>
        </div>
    </div>
{% endblock %}

c19/gift/templates/gift/comment_create.html
{% extends parent_template|default:"base.html" %}
{% load static %}

{% block content %}
    <div class="card col-md-8 mx-md-auto p-0">
        <div class="card-header text-center bg-primary">
            <h3 class="text-secondary">Guesses or Comments</h3>
        </div>
        <img class="card-img-top" src="{% static gift.get_image_filename %}" alt="Image of {{ gift }}">
        <div class="card-body">
            <div class="h4 text-success col-md-10 mt-3 mx-md-auto">{{ gift.description }}</div>
            {% for comment in gift.get_comments %}
                <p class="col-md-10 text-blue card-text mx-md-auto">{{ comment.display }}</p>
            {% endfor %}
            <form action="{% url 'gift:add_comment' gift.gift_number %}" method="post">
                {% csrf_token %}
                <div class="form-group col-md-10 mx-md-auto mt-3">
                    <label for="comment">Enter a new guess or comment below:</label>
                    <textarea class="form-control" id="comment" name="comment_text" rows="3"></textarea>
                </div>
                <div class="col-12 text-center">
                    <button class="btn-outline-success btn-lg text-center" type="submit">Submit</button>
                </div>
            </form>
        </div>
    </div>
{% endblock %}

c19/gift/templates/gift/comment_delete.html
{% extends parent_template|default:"gift/base_gift_detail.html" %}
{% load static %}

{% block gift-detail-page-specific-content %}
    <h5 class="card-title">Confirm Deletion:</h5>
    <p class="card-text">
        Do you really want to delete the remark: "{{ selected_comment.display }}"?
    </p>
    <form action="{% url 'gift:delete_comment' gift.gift_number selected_comment.pk %}?next={{ next_url }}" method="post">
        {% csrf_token %}
        <div class="row no-gutters">
            <input type="hidden" name="next" value="{{ next_url }}">
            <button class="btn btn-outline-success col-md-6" name='button' value='delete' type="submit">
                Yes, Delete It
            </button>
            <button class="btn btn-outline-success col-md-6" name="button" value="cancel" type="submit">
                No, Cancel Deletion
            </button>
        </div>
    </form>

{% endblock %}

c19/gift/templates/gift/comment_edit.html
{% extends parent_template|default:"gift/base_gift_detail.html" %}
{% load static %}

{% block gift-detail-page-specific-content %}
    <h5 class="card-title">Edit or Delete Your Remark</h5>
    <p class="card-text">
        To edit your remark, enter the new text in the entry box below and click the 'Save Changes' button.
        To delete it click the 'Delete...' button and confirm the deletion on the page that appears. To
        change nothing and return to the previous page simply click the 'Cancel' button.
    </p>
    <form action="{% url 'gift:edit_comment' gift.gift_number selected_comment.pk %}" method="post">
        {% csrf_token %}
        <textarea class="col mb-3" id="comment" name="comment_text">{{ selected_comment.comment }}</textarea>
        <div class="row no-gutters">
            <button class="btn btn-outline-success col-md-4" type="submit">Save Changes</button>
            {% if next_url %}
                <a class="btn btn-outline-success col-md-4"
                   href="{% url 'gift:delete_comment' gift.gift_number selected_comment.pk %}?next={{ next_url }}">
                    Delete...
                </a>
                <a class="btn btn-outline-success col-md-4" href="{{ next_url }}">Cancel</a>
            {% else %}
                <a class="btn btn-outline-success col-md-4"
                   href="{% url 'gift:delete_comment' gift.gift_number selected_comment.pk %}">
                    Delete...
                </a>
                <a class="btn btn-outline-success col-md-4" href="{% url 'gift:home' %}">Cancel</a>
            {% endif %}
        </div>
    </form>
{% endblock %}

c19/gift/templates/gift/gift_detail.html
{% extends parent_template|default:"gift/base_gift_detail.html" %}
{% load static %}

{% block gift-detail-page-specific-content %}
        {% if gift.selected  %}
            <form action="{% url 'gift:change_mind' gift.gift_number %}" method="post">
                {% csrf_token %}
                <div class="row no-gutter justify-content-between">
                    {% if gift.receiver == user %}
                        <button class="btn btn-outline-success btn-lg col-sm-4 mt-3 mt-sm-0 mx-3"
                                type="submit" name="button" value="change">Change Mind</button>
                    {% else %}
                        <div class="col-sm-4"></div>        <!-- place holder for missing button -->
                    {% endif %}
                    <button class="btn btn-outline-success btn-lg col-sm-4 mt-3 mt-sm-0 mx-3"
                            type="submit" name="button" value="remark">Add Remark</button>
                </div>
            </form>
        {% else %}
            <form action="{% url 'gift:select' gift.gift_number %}" method="post">
                {% csrf_token %}
                <div class="row no-gutter justify-content-between">
                    {% if not user_has_gift %}
                        <button class="btn btn-outline-success btn-lg col-sm-4 mt-3 mt-sm-0"
                                type="submit" name="button" value="select">Select</button>
                    {% else %}
                        <div class="col-sm-4"></div>        <!-- place holder for missing button -->
                    {% endif %}
                    <button class="btn btn-outline-success btn-lg col-sm-4 mt-3 mt-sm-0 mx-3"
                            type="submit" name="button" value="remark">Add Remark</button>
                </div>
            </form>
        {% endif %}
        <div class="text-center">
            <a class="btn btn-outline-success btn-block btn-lg" href="{% url 'gift:home' %}">Return to Gift List</a>
        </div>
{% endblock %}

c19/gift/templates/gift/gift_list.html
{% extends parent_template|default:"base.html" %}
{% load static %}

{% block content %}
    <div class="row mx-1 mx-md-5 mb-3 info-box text-blue">
        <a class="d-md-none" data-toggle="collapse" href="#welcome"><span>Welcome... </span></a>
        <div class="d-md-none collapse" id="welcome">
            <p><i>Welcome back to this year's version of our family Christmas website! I haven't changed the look and
                feel of the website this year, just updated the gifts and activities. The Christmas memories that
                appear on each page are getting pretty old, though. Please add some new ones by clicking on
                "Memories" in the menu.</i></p>
            <p><i>As always, select a gift based on my wonderful and obvious clues. Make guesses as to what they
                might be, or make other comments, by clicking a "Remark" button. I'm planning on the same three
                activities as we had last year. Click the "Activities" entry in the menu from time to time to check for
                anything new.</i></p>
            <p><i>Again, the little black thing in all of the gift pictures is my camera's lens cap. It is 2 1/4"
                across and is there to give you an idea of package sizes.</i></p>
        </div>
        <div class="d-none d-md-inline">
            <p><i>Welcome back to this year's version of our family Christmas website! I haven't changed the look and
                feel of the website this year, just updated the gifts and activities. The Christmas memories that
                appear on each page are getting pretty old, though. Please add some new ones by clicking on
                "Memories" in the menu.</i></p>
            <p><i>As always, select a gift based on my wonderful and obvious clues. Make guesses as to what they
                might be, or make other comments, by clicking a "Remark" button. I'm planning on the same three
                activities as we had last year. Click the "Activities" entry in the menu from time to time to check for
                anything new.</i></p>
            <p><i>Again, the little black thing in all of the gift pictures is my camera's lens cap. It is 2 1/4"
                across and is there to give you an idea of package sizes.</i></p>
        </div>
    </div>
    <div class="row px-3">
        {% for gift in gifts %}
            <div class="card col-12 pb-3 mb-3">
                <div class="row">
                    <!-- Left Column or Top Line: gift image and caption -->
                    <div class="col-sm-4 col-md-3 pl-0">
                        {% if gift.selected %}
                            <a href="{% url 'gift:gift_detail' gift.gift_number %}" title="Click for larger image.">
                                <img class="w-100 border border-primary gift-img d-none d-md-block"
                                     src="{% static gift.get_image_filename %}" alt="Image of {{ gift }}">
                            </a>
                            <h4 class="text-primary">{{ gift }}
                                <a class="d-inline d-md-none" href="{% url 'gift:gift_detail' gift.gift_number %}">
                                    See it...
                                </a>
                            </h4>
                            <p class="text-primary mx-auto">Selected by {{ gift.receiver_name }}</p>
                        {% else %}
                            <a href="{% url 'gift:gift_detail' gift.gift_number %}" title="Click for larger image.">
                                <img class="w-100 border border-success gift-img d-none d-md-block"
                                     src="{% static gift.get_image_filename %}" alt="Image of {{ gift }}">
                            </a>
                            <h4 class="text-success">{{ gift }}
                                <a class="d-inline d-md-none" href="{% url 'gift:gift_detail' gift.gift_number %}">
                                    See it...
                                </a>
                            </h4>
                            <p class="text-success mx-auto">Unselected</p>
                        {% endif %}
                    </div>

                    <!-- Middle Column or Middle Line: gift clue and comments -->
                    <div class="col-sm">
                        <p class="text-success">{{ gift.description|safe }}</p>
                        {% if gift.get_comments %}
                            {% if gift.get_comments|length > 4 %}
                                <a data-toggle="collapse" href="#Gift{{ gift.gift_number }}_remarks">Toggle remarks...</a>
                                <div class="collapse" id="Gift{{ gift.gift_number }}_remarks">
                                    {% for comment in gift.get_comments %}
                                        {% if comment.user == user %}
                                            <p class="comment">
                                                {{ comment.display }}
                                                <a href="{% url 'gift:edit_comment' gift.gift_number comment.pk %}"> (Edit...)</a>
                                            </p>
                                        {% else %}
                                            <p class="comment">{{ comment.display }}</p>
                                        {% endif %}
                                    {% endfor %}
                                </div>
                            {% else %}
                                {% for comment in gift.get_comments %}
                                    {% if comment.user == user %}
                                        <p class="comment">
                                            {{ comment.display }}
                                            <a href="{% url 'gift:edit_comment' gift.gift_number comment.pk %}"> (Edit...)</a>
                                        </p>
                                    {% else %}
                                        <p class="comment">{{ comment.display }}</p>
                                    {% endif %}
                                {% endfor %}
                            {% endif %}
                        {% endif %}
                    </div>

                    <!-- Third Column or Third Line: Buttons -->
                    <div class="col-sm-3 col-md-2 mt-3">
                        {% if gift.selected %}
                            <form action="{% url 'gift:change_mind' gift.gift_number %}" method="post">
                                {% csrf_token %}
                                {% if gift.receiver == user %}
                                    <button class="btn btn-outline-success btn-block"
                                            type="submit" name="button" value="change">Change</button>
                                {% endif %}
                                <button class="btn btn-outline-success btn-block"
                                        type="submit" name="button" value="remark">Remark</button>
                            </form>
                        {% else %}
                            <form action="{% url 'gift:select' gift.gift_number %}" method="post">
                                {% csrf_token %}
                                {% if not user_has_gift %}
                                    <button class="btn btn-outline-success btn-block"
                                            type="submit" name="button" value="select">Select</button>
                                {% endif %}
                                <button class="btn btn-outline-success btn-block"
                                        type="submit" name="button" value="remark">Remark</button>
                            </form>
                        {% endif %}
                    </div>
                </div>
            </div>
        {% endfor %}
    </div>
{% endblock %}